docker_nginx:
  container_name: docker_nginx
  image: nginx:latest
  volumes:
    - /docker/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - /docker/volumes/nginx/nginx.key:/etc/nginx/nginx.key:ro
    - /docker/volumes/nginx/nginx.crt:/etc/nginx/nginx.crt:ro
    - /docker/volumes/nginx/conf.d:/etc/nginx/conf.d:ro
    - /docker/volumes/nginx/index.html:/usr/share/nginx/html/index.html:ro
  ports:
    - "80:80"
    - "443:443"
