# nginx playbook
- hosts: docker01.example.com
  become: yes
  become_method: sudo
  vars:
    dockerhost_user: ec2-user
    nginx_hostname: docker01.example.com
  roles:
    - { role: docker-host }
    - { role: nginx }
