---
# tasks file for drupal
- name: "Create conf directory"
  file: path={{ item.path }} state=directory recurse=yes
  with_items:
    - { path: '/docker/{{ drupal_name }}' }

- name: "Create nginx drupal.conf from template"
  template: src=nginx.conf.j2 dest=/docker/volumes/nginx/conf.d/{{ drupal_name }}.conf
  notify: 
   - reload nginx

- name: "Create docker-compose.yml from template"
  template: src=docker-compose.yml.j2 dest=/docker/{{ drupal_name }}/docker-compose.yml

- name: "Copy upstart script"
  template: src=docker_drupal.conf.j2 dest=/etc/init/docker_{{ drupal_name }}.conf

- name: "Start nginx container"
  service: name=docker_{{ drupal_name }} state=started enabled=yes
